package com.example;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'BIAMRIAN-PC' at '9/27/16 5:16 PM' with Gradle 2.14.1
 *
 * @author BIAMRIAN-PC, @date 9/27/16 5:16 PM
 */
public class App {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
		System.out.println("Hi, this is a gradle project");
	}
}
